### ISSUE TITLE
Accept a list file for the signoff tool

### ISSUE THREAD

**Issue by jcjones** [mozilla/crlite#110]
If we can't fit all the hosts into an environment variable, then we might want to load them from a file.

@smarnach : Any thoughts on where we should store such a file and load it? A URL to somewhere trusted? I am unsure what to do here.

**Comment by smarnach** [comment]
A quick list of options I can think of:

* A ConfigMap, which can be mounted as a local file in a pod. I think there's a limit of 1 or 2MB for ConfigMaps, so that should be enough for something like 50.000 sites.
* Bake it into the container image. Would work, but meh.
* A Cloud Storage bucket – either the one we already have, or a new one (which could even be public). In the interest of clearer separation between publication and verification, maybe it should be a separate one. It could even be world-readable, since we wouldn't really mind if people see our list of Alexa Top 500 sites or whatever.

I think my preference would be the last option – a separate, public Cloud Storage bucket, so we can simply pass a URL to the signoff job.

**Comment by jcjones** [comment]
Sounds good to me to do the last option.

So there's two ways to get at the GCS. We can either really use a public URL, or we could provide a bucket name and path and download via the API.

My preference would be public URL -- what's yours, @smarnach ?

**Comment by smarnach** [comment]
I agree, a public URL seems like the easiest and most flexible option. I'll create a new bucket for it and upload some list of domains.

**Comment by smarnach** [comment]
I've created a bucket and added some random list of top 500 sites I found on the internet: https://smallcultfollowing.com/babysteps/blog/2018/11/01/after-nll-interprocedural-conflicts/

I thought I made this completely public, but it still seems to require to be authenticated. I'll investigate later – you can simply start with some URL you control for testing.

**Comment by smarnach** [comment]
Looks like I got the link wrong. :)

**Comment by smarnach** [comment]
Here's the correct link that works without autentication: https://storage.googleapis.com/crlite-verification-domains/moz-top500.txt

**Comment by jcjones** [comment]
As a note, we'll want to also include all dangerous domains for Firefox users, too.

**Comment by smarnach** [comment]
We could probably derive some of the domain names from https://searchfox.org/mozilla-central/source/security/manager/ssl/StaticHPKPins.h. One problem is that the file contains many wildcard domains. E.g. the Remote Settings domain isn't listed directly, but is covered via `*.services.mozilla.com`.

Maybe we want to be able to configure a list of URLs? This would allow us to independently update domain lists from different sources without having to concatenate them into a single file.

The list I added is certainly not ideal – it was just the first thing I could find that was readily available as a CSV file.

**Comment by smarnach** [comment]
I've uploaded a first version of a list of Mozilla services domain at https://storage.googleapis.com/crlite-verification-domains/mozilla-services-domains.txt. This list was extracted from the data at https://github.com/mozilla-services/foxsec/tree/master/services/metadata using the command line

    jq -r '.sites[].urls[] | select(.status == "production").url' *.json | sort -u > mozilla-services-domains.txt

The data is manually maintained and not necessarily up to date, but should cover many of the important domains we care about.

The llist of popular domain names was retrieved from https://moz.com/top500, by the way. I just noticed that the `moz` in the file name may be confusing.

**Comment by jcjones** [comment]
Supported added to moz_crlite_query in v0.3.0: https://pypi.org/project/moz-crlite-query/0.3.0/

Thanks. I didn't know where it was coming from :)

My plan is to take a list of URLs via environment, like I do with the CT Logs. Then for each URL provided, download it, and pass those to moz_crlite_query.

Note that it's serial, no threading and no caching, so large lists are not quick. But then again, it doesn't really need to be.... and I can always speed it up in the future.

Thanks for the work making the services list -- it looks similar but more complete to one I started a few weeks ago. Yours is better definitely. It does have some issues though, not all the names are hosting services I can reach from home, at least, A couple even blackhole. Yay! But `--check-not-revoked` allows for nonworking services. It only errors if one is revoked.
