### ISSUE TITLE
Change publisher intermediate sign-off logic

### ISSUE THREAD

**Issue by jcjones** [mozilla/crlite#112]
Unenrolling a CA from CRLite should be automatic. Enrolling a CA into CRLite should require some manner of human intervention, to ensure the addition makes sense.

**Comment by jcjones** [comment]
This should also document all the failure and success cases, and how they interplay with CRLite at the User Agent side.

**Comment by jschanck** [comment]
Enrollment is now stored as per-filter metadata.
