### ISSUE TITLE
Include CA certs in filters

### ISSUE THREAD

**Issue by jschanck** [mozilla/crlite#266]
Firefox doesn't query CRLite on CA certs, but other applications might. We don't communicate the fact that we're not including CA certs in our filter metadata, which means other applications could get false positives if they query CA certs.

In the interest of making our filters broadly usable, let's include CA certs. The overall impact on filter size will be small.

**Comment by jcjones** [comment]
The original concern with non-end-entity certs was that since they don't include SCTs, it wasn't clear, programmatically, how to tell if a given certificate should be expected to be within the dataset. Is that going to somehow derivable?
