### ISSUE TITLE
Don't infinite loop resolving false positives

### ISSUE THREAD

**Issue by jcjones** [mozilla/crlite#51]
This command failed to resolve its false positives: `certs_to_crlite.py -knownPath /Volumes/Battlestar/crlite-processing/20200312-0/known -revokedPath /Volumes/Battlestar/crlite-processing/20200312-0/revoked /Volumes/Battlestar/crlite-processing/20200312-0/ -previd /Volumes/Battlestar/crlite-processing/20200307-0/mlbf/ -onlyUseCache`

```
[...]
DEBUG:filtercascade:Took 0.789 ms to process layer 97596 with bit count 14400
DEBUG:filtercascade:Initializing the 97597-depth layer. err=0.5 include_len=127 size=14400 hashes=1
DEBUG:filtercascade:Processing false positives
DEBUG:filtercascade:Took 0.863 ms to process layer 97597 with bit count 14400
DEBUG:filtercascade:Initializing the 97598-depth layer. err=0.5 include_len=127 size=14400 hashes=1
DEBUG:filtercascade:Processing false positives
DEBUG:filtercascade:Took 0.62 ms to process layer 97598 with bit count 14400
DEBUG:filtercascade:Initializing the 97599-depth layer. err=0.5 include_len=127 size=14400 hashes=1
DEBUG:filtercascade:Processing false positives
DEBUG:filtercascade:Took 0.669 ms to process layer 97599 with bit count 14400
DEBUG:filtercascade:Initializing the 97600-depth layer. err=0.5 include_len=127 size=14400 hashes=1
DEBUG:filtercascade:Processing false positives
DEBUG:filtercascade:Took 0.658 ms to process layer 97600 with bit count 14400
DEBUG:filtercascade:Initializing the 97601-depth layer. err=0.5 include_len=127 size=14400 hashes=1
DEBUG:filtercascade:Processing false positives
DEBUG:filtercascade:Took 0.646 ms to process layer 97601 with bit count 14400
[...]
```

It's unclear what really happened here, but in any case, if we're producing dozens of layers -- let alone tens of thousands -- there's something wrong with the dataset and we should abort cleanly while logging as much info to debug with as possible.

**Comment by smarnach** [comment]
A one-character fix would be to change `>` to `>=` in [this line](https://github.com/mozilla/filter-cascade/blob/90532fc36e3ef809eec1051cd47924737ea95c64/filtercascade/__init__.py#L215).

**Comment by jschanck** [comment]
closing this as we no longer use certs_to_crlite.py
