### ISSUE TITLE
Staging should auto-publish to Kinto Dev

### ISSUE THREAD

**Issue by jcjones** [mozilla/crlite#88]
There's a developer Kinto instance at https://kinto.dev.mozaws.net/v1/ which is generally blank. The publisher and approver's defaults should be to publish and approve at that instance, to test end-to-end.

**Comment by smarnach** [comment]
Let's test end-to-end in the stage environment. We will spin up a stage env owned by CloudOps. Once CRLite is mostly stable, we can probably get rid of the current dev env, and test changes in the stage env instead.

**Comment by jcjones** [comment]
Then there's no action to take here.
